---
- name: update tooling, todo, nginx and db servers
  hosts: tooling, todo, nginx, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
   - name: update apt cache
     apt: update_cache=yes
   - name: ensure wireshark is at the latest version
     apt:
      name: wireshark
      state: latest

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
     - name: ensure wireshark is at the latest version
       apt:
         name: wireshark
         state: latest     