[uat-webservers]
172.31.13.108 ansible_user='ec2-user' ansible_private_key_file=/home/ubuntu/joe-keypair.pem
172.31.15.135 ansible_user='ec2-user' ansible_private_key_file=/home/ubuntu/joe-keypair.pem