---
- name: install apache
  become: true
  become_user: root
  ansible.builtin.yum:
    name: httpd
    state: present

- name: install git
  become: true
  become_user: root
  ansible.builtin.yum:
    name: git
    state: present

- name: clone a repo
  ansible.builtin.git:
     repo: https://github.com/jtoguntoye/tooling.git
     dest: /var/www/html
     force: yes

- name: copy html content one level up
  become: true
  become_user: root
  command: cp -r /var/www/html/html /var/www/

- name: start service httpd, if not started
  become: true
  become_user: root
  ansible.builtin.service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent    