--- 
  - name: Import common files
    import_playbook: ../static-assignments/common.yml
    tags:
      - always   
        
  - name: Include dynamic variables
    include: ../dynamic-assignments/env-vars.yml
    tags:
        - always

  - name: database setup
    import_playbook: ../static-assignments/uat-mysqlserver.yml      

  - name: webserver assignment
    import_playbook: ../static-assignments/uat-webservers.yml

  
  - name: loadbalancer assignments
    import_playbook: ../static-assignments/loadbalancers.yml
    when: load_balancer_is_required 
