---
- name: include dynamic variables
  hosts: all
  tasks:
    - import_playbook: ../static-assignments/common.yml
    - include_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always   

- name: webserver assignment
  hosts: uat-webservers
  tasks:
   - import_playbook: ../static-assignments/uat-webservers.yml